[package]
name = "i18n"
version = "0.1.0"
edition = "2021"

[dependencies]
i18n-macros = { path = "./i18n-macros" }
i18n-loader = { path = "./i18n-loader" }

[workspace]
members = [
  "i18n-loader",
  "i18n-macros",
]
